name: 📦 New Example Pack
description: Submit a new Processing example pack
labels: ["new-contribution"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for your new example pack contribution to Processing!

        An example package is a set of sample Processing sketches bundled together that can be downloaded and installed so the user can access them from the Processing Examples window.

        If you need help creating an example pack, see the [Examples Overview](https://github.com/processing/processing/wiki/Examples-Overview) or ask on the [Processing Forum](https://discourse.processing.org/).

        Please provide the necessary information below.

  - type: input
    id: properties_url
    attributes:
      label: Properties File URL
      description: URL of your `examples.properties` file.
      placeholder: https://
    validations:
      required: true
  - type: input
    id: documentation_url
    attributes:
      label: Home Page URL
      description: URL of the home page for your example pack.
      placeholder: https://
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Please read the [Examples Overview](https://github.com/processing/processing/wiki/Examples-Overview) and make sure that your example pack follows the guidelines.
  - type: checkboxes
    id: guidelines_confirmation
    attributes:
      label: Guidelines Confirmation
      description: I confirm that I have read the [Examples Overview](https://github.com/processing/processing/wiki/Examples-Overview) and that my example pack follows the guidelines.
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Once you submit this form, the `examples.properties` file at the provided URL will be parsed and validated.

        The result of this validation will be added to this issue:
        - If valid, a pull request will automatically be created to add your example pack to the repository.
        - If invalid, a comment will be added with details of the error. You will need to fix the file and resubmit.
  - type: hidden
    id: contribution_type
    attributes:
      value: examples