blank_issues_enabled: true
contact_links:
  - name: 🐛 Processing Issues
    url: https://github.com/processing/processing/issues
    about: Report issues with Processing here.
  - name: 🌐 Processing Website Issues
    url: https://github.com/processing/processing-website/issues
    about: Report issues with the processing.org website here.
  - name: 📚 Examples Issues
    url: https://github.com/processing/processing-examples/issues
    about: Report issues with the official Processing examples here.
  - name: 💬 Forum
    url: https://discourse.processing.org/
    about: Have other questions about using Processing? Ask them here!
  - name: 🌸 p5.js Issues
    url: https://github.com/processing/p5.js/issues
    about: Report issues with p5.js here.
